##########
# dman   #
##########
[dman.info]
steamcmd_path = 'steamcmd'
servers_path = 'servers'


##########
# user   #
##########
[user.info]
steam_username = 'STEAM_USERNAME'


###########
# servers #
###########
[servers.list]
default_instance_1 = true
default_instance_2 = false # this server has been disabled (stopped)
# you can add more instances just keep to the format (all lowercase)