############
#   dman   #
############
[dman.info]
config_name = 'dman.toml'
dman_path = '~/dman'
steamcmd_path = '~/dman/steamcmd'


############
#   user   #
############
[user.info]
steam_username = 'STEAM_USERNAME'
servers_path = '~/dman/servers'
