##########
# dman   #
##########
[dman.info]
steamcmd_path = 'steamcmd' # these are both located in the app/ dir
servers_path = 'servers' # the app/ dir is created after changing default username and password


##########
# user   #
##########
[user.info]
steam_username = 'STEAM_USERNAME' # change these!
steam_password = 'STEAM_PASSWORD'


###########
# servers #
###########
[servers.list]
default_instance_1 = true
default_instance_2 = false # this server has been disabled (stopped)
# you can add more instances just keep to the format (all lowercase)