############
#  Server  #
############
[server.info]
port = 2302 # default game port
discord_webhook = '' # mod download updates can be posted to discord
client_mods = '' # put mod ids to download and install mods, format is '@mod1;@mod2;@mod3'
server_mods = '' # same for server mods :3
logs='' # enable logs if desired, log options include the following: '-dologs -adminlog -netlog'
